//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextCompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextCompiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_compiler_8167773 {
            get {
                object obj = ResourceManager.GetObject("free-icon-compiler-8167773", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_compiler_81677731 {
            get {
                object obj = ResourceManager.GetObject("free-icon-compiler-81677731", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_compiler_81677732 {
            get {
                object obj = ResourceManager.GetObject("free-icon-compiler-81677732", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_copy_3979334 {
            get {
                object obj = ResourceManager.GetObject("free-icon-copy-3979334", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_diskette_747439 {
            get {
                object obj = ResourceManager.GetObject("free-icon-diskette-747439", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_new_page_6604902 {
            get {
                object obj = ResourceManager.GetObject("free-icon-new-page-6604902", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_open_folder_5082610 {
            get {
                object obj = ResourceManager.GetObject("free-icon-open-folder-5082610", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap free_icon_undo_7133518 {
            get {
                object obj = ResourceManager.GetObject("free-icon-undo-7133518", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///   &lt;title&gt;Guide&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h1 align=center&gt;Help&lt;/h1&gt;
        ///    &lt;font size=4&gt;
        ///	&lt;h2&gt;Working with Files&lt;/h2&gt;
        ///	&lt;h3&gt;Creating a New File&lt;/h3&gt;
        ///	&lt;p&gt;In the &lt;b&gt;File&lt;/b&gt; tab, select &lt;i&gt;New&lt;/i&gt; (Ctrl+N)&lt;/p&gt;
        ///	&lt;h3&gt;Opening a File&lt;/h3&gt;
        ///	&lt;p&gt;In the &lt;b&gt;File&lt;/b&gt; tab, select &lt;i&gt;Open&lt;/i&gt; (Ctrl+O), or drag and drop a file into the editor window&lt;/p&gt;
        ///	&lt;h3&gt;Saving a File&lt;/h3&gt;
        ///	&lt;p&gt;In the &lt;b&gt;File&lt;/b&gt; tab, select &lt;i&gt;Save&lt;/i&gt; (Ctrl+S) or &lt;i&gt;Save As&lt;/i&gt; to save under a different [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helpbutton_85772 {
            get {
                object obj = ResourceManager.GetObject("helpbutton_85772", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_вставить_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-вставить-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_вырезать_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-вырезать-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_начало_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-начало-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_отменить_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-отменить-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_отменить_51 {
            get {
                object obj = ResourceManager.GetObject("icons8-отменить-51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///   &lt;title&gt;Руководство&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h1 align=center&gt;Справка&lt;/h1&gt;
        ///    &lt;font size=4&gt;
        ///	&lt;h2&gt;Работа с файлами&lt;/h2&gt;
        ///	&lt;h3&gt;Создание нового файла&lt;/h3&gt;
        ///	&lt;p&gt;Во вкладке &lt;b&gt;Файл&lt;/b&gt; выберите &lt;i&gt;Создать&lt;/i&gt; (Ctrl+N)&lt;/p&gt;
        ///	&lt;h3&gt;Открытие файла&lt;/h3&gt;
        ///	&lt;p&gt;Во вкладке &lt;b&gt;Файл&lt;/b&gt; выберите &lt;i&gt;Открыть&lt;/i&gt; (Ctrl+O), либо перетащите файл в окно редактирования &lt;/p&gt;
        ///	&lt;h3&gt;Сохранение файла&lt;/h3&gt;
        ///	&lt;p&gt;Во вкладке &lt;b&gt;Файл&lt;/b&gt; выберите &lt;i&gt;Сохранить&lt;/i&gt; (Ctr [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Справка {
            get {
                return ResourceManager.GetString("Справка", resourceCulture);
            }
        }
    }
}
